version: '3.4'

services:
  eslintvisitorkeys:
    image: eslintvisitorkeys
    build:
      context: node_modules/eslint-visitor-keys
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 3000:3000
